apiVersion: batch/v1
kind: Job
metadata:
  name: client-simple-job
spec:
  template:
    spec:
      containers:
      - name: eon-client
        image: sajmon/eon-client
        command: [
          "eon-client",
          "--stdout",
          "--log-level", "debug",
          "--script-file", "/mnt/scripts/script.yaml"
        ]
        volumeMounts:
        - name: scripts
          mountPath: "/mnt/scripts"
          readOnly: true
      volumes:
      - name: scripts
        configMap:
          name: simple-wait
          items:
          - key: "simple.yaml"
            path: "simple-wait-script"
      restartPolicy: Never
  backoffLimit: 4