apiVersion: v1
kind: Service
metadata:
  name: eon-bootstrap
  labels:
    app: bootstrap-node
spec:
  type: ClusterIP
  clusterIP: 10.96.0.1
  ports:
  - port: 22137
    protocol: TCP
  selector:
    app: bootstrap-node
